import { Injectable, Logger } from '@nestjs/common';
import { OnEvent } from '@nestjs/event-emitter';
import { OnboardingStepId } from '../../domain/onboarding-progress.entity';
import { CompleteStepUseCase } from '../use-cases/complete-step.use-case';
import { WhatsAppMessagingAdapter } from '../../../common/messaging/whatsapp-messaging.adapter';
import { TelegramMessagingAdapter } from '../../../common/messaging/telegram-messaging.adapter';
import { MessagingPlatforms } from '../../../common/messaging/domain/constants/messaging-platforms.enum';
import { IMessagingService } from '../../../common/messaging/messaging.service.interface';

/**
 * Event payloads for onboarding step detection.
 */
export interface OnboardingEvent {
  userId: string;
  organizationId: string;
  senderPhoneNumber: string;
  platform: MessagingPlatforms;
}

/**
 * @deprecated Use OnboardingEvent instead
 */
export interface TransactionCreatedEvent extends OnboardingEvent {}
export interface DebtCreatedEvent extends OnboardingEvent {}
export interface MemberAddedEvent extends OnboardingEvent {}
export interface ReportGeneratedEvent extends OnboardingEvent {}

/**
 * Event Listener that detects when users complete onboarding steps.
 * Automatically updates progress when relevant actions are performed.
 */
@Injectable()
export class OnboardingEventListener {
  private readonly logger = new Logger(OnboardingEventListener.name);

  constructor(
    private readonly completeStepUseCase: CompleteStepUseCase,
    private readonly whatsAppAdapter: WhatsAppMessagingAdapter,
    private readonly telegramAdapter: TelegramMessagingAdapter,
  ) {}

  private getMessagingService(platform: MessagingPlatforms): IMessagingService {
    return platform === MessagingPlatforms.TELEGRAM
      ? this.telegramAdapter
      : this.whatsAppAdapter;
  }

  @OnEvent('transaction.created')
  async handleTransactionCreated(payload: OnboardingEvent): Promise<void> {
    this.logger.log(`[Onboarding] Transaction created by user ${payload.userId}`);
    
    await this.completeStep(
      payload.userId,
      payload.organizationId,
      OnboardingStepId.CREATE_FIRST_TRANSACTION,
      payload.senderPhoneNumber,
      payload.platform,
    );
  }

  @OnEvent('debt.created')
  async handleDebtCreated(payload: OnboardingEvent): Promise<void> {
    this.logger.log(`[Onboarding] Debt created by user ${payload.userId}`);

    await this.completeStep(
      payload.userId,
      payload.organizationId,
      OnboardingStepId.TRACK_FIRST_DEBT,
      payload.senderPhoneNumber,
      payload.platform,
    );
  }

  @OnEvent('member.added')
  async handleMemberAdded(payload: OnboardingEvent): Promise<void> {
    this.logger.log(`[Onboarding] Member added by user ${payload.userId}`);
    
    await this.completeStep(
      payload.userId,
      payload.organizationId,
      OnboardingStepId.ADD_TEAM_MEMBER,
      payload.senderPhoneNumber,
      payload.platform,
    );
  }

  @OnEvent('report.generated')
  async handleReportGenerated(payload: OnboardingEvent): Promise<void> {
    this.logger.log(`[Onboarding] Report generated by user ${payload.userId}`);
    
    await this.completeStep(
      payload.userId,
      payload.organizationId,
      OnboardingStepId.GENERATE_REPORT,
      payload.senderPhoneNumber,
      payload.platform,
    );
  }

  @OnEvent('subscription.created')
  async handleSubscriptionCreated(payload: OnboardingEvent): Promise<void> {
    this.logger.log(`[Onboarding] Subscription created for user ${payload.userId}`);
    
    await this.completeStep(
      payload.userId,
      payload.organizationId,
      OnboardingStepId.SUBSCRIBE,
      payload.senderPhoneNumber,
      payload.platform,
    );
  }

  private async completeStep(
    userId: string,
    organizationId: string,
    stepId: OnboardingStepId,
    senderPhoneNumber: string,
    platform: MessagingPlatforms,
  ): Promise<void> {
    try {
      const result = await this.completeStepUseCase.execute({
        userId,
        organizationId,
        stepId,
      });

      if (result.success && result.completionMessage) {
        // Send congratulation message
        let message = result.completionMessage;

        if (result.nextStep) {
          // Add next step info
          const tipMessage = 'tipMessage' in result.nextStep 
            ? result.nextStep.tipMessage 
            : '';
          message += `\n\n${tipMessage}`;
        } else if (result.isOnboardingCompleted) {
          message += `\n\n🎊 *Félicitations !* Vous avez terminé le tutoriel !`;
        }

        const messagingService = this.getMessagingService(platform);
        await messagingService.sendMessage(senderPhoneNumber, message);
      }
    } catch (error) {
      this.logger.error(`Failed to complete onboarding step ${stepId}`, error);
    }
  }
}
