import { Injectable, Logger } from '@nestjs/common';
import { OnEvent } from '@nestjs/event-emitter';
import { OnboardingStepId } from '../../domain/onboarding-progress.entity';
import { CompleteStepUseCase } from '../use-cases/complete-step.use-case';
import { WhatsAppService } from '../../../common/whatsapp/whatsapp.service';

/**
 * Event payloads for onboarding step detection.
 */
export interface TransactionCreatedEvent {
  userId: string;
  organizationId: string;
  senderPhoneNumber: string;
}

export interface MemberAddedEvent {
  userId: string;
  organizationId: string;
  senderPhoneNumber: string;
}

export interface ReportGeneratedEvent {
  userId: string;
  organizationId: string;
  senderPhoneNumber: string;
}

/**
 * Event Listener that detects when users complete onboarding steps.
 * Automatically updates progress when relevant actions are performed.
 */
@Injectable()
export class OnboardingEventListener {
  private readonly logger = new Logger(OnboardingEventListener.name);

  constructor(
    private readonly completeStepUseCase: CompleteStepUseCase,
    private readonly whatsAppService: WhatsAppService,
  ) {}

  @OnEvent('transaction.created')
  async handleTransactionCreated(payload: TransactionCreatedEvent): Promise<void> {
    this.logger.log(`[Onboarding] Transaction created by user ${payload.userId}`);
    
    await this.completeStep(
      payload.userId,
      payload.organizationId,
      OnboardingStepId.CREATE_FIRST_TRANSACTION,
      payload.senderPhoneNumber,
    );
  }

  @OnEvent('member.added')
  async handleMemberAdded(payload: MemberAddedEvent): Promise<void> {
    this.logger.log(`[Onboarding] Member added by user ${payload.userId}`);
    
    await this.completeStep(
      payload.userId,
      payload.organizationId,
      OnboardingStepId.ADD_TEAM_MEMBER,
      payload.senderPhoneNumber,
    );
  }

  @OnEvent('report.generated')
  async handleReportGenerated(payload: ReportGeneratedEvent): Promise<void> {
    this.logger.log(`[Onboarding] Report generated by user ${payload.userId}`);
    
    await this.completeStep(
      payload.userId,
      payload.organizationId,
      OnboardingStepId.GENERATE_REPORT,
      payload.senderPhoneNumber,
    );
  }

  @OnEvent('subscription.created')
  async handleSubscriptionCreated(payload: { userId: string; organizationId: string; senderPhoneNumber: string }): Promise<void> {
    this.logger.log(`[Onboarding] Subscription created for user ${payload.userId}`);
    
    await this.completeStep(
      payload.userId,
      payload.organizationId,
      OnboardingStepId.SUBSCRIBE,
      payload.senderPhoneNumber,
    );
  }

  private async completeStep(
    userId: string,
    organizationId: string,
    stepId: OnboardingStepId,
    senderPhoneNumber: string,
  ): Promise<void> {
    try {
      const result = await this.completeStepUseCase.execute({
        userId,
        organizationId,
        stepId,
      });

      if (result.success && result.completionMessage) {
        // Send congratulation message
        let message = result.completionMessage;

        if (result.nextStep) {
          // Add next step info
          const tipMessage = 'tipMessage' in result.nextStep 
            ? result.nextStep.tipMessage 
            : '';
          message += `\n\n${tipMessage}`;
        } else if (result.isOnboardingCompleted) {
          message += `\n\n🎊 *Félicitations !* Vous avez terminé le tutoriel !`;
        }

        await this.whatsAppService.sendMessage(senderPhoneNumber, message);
      }
    } catch (error) {
      this.logger.error(`Failed to complete onboarding step ${stepId}`, error);
    }
  }
}
